
#
# primitive makefile to build ed2k_hash with
# Mingw32
#

CC=gcc
CFLAGS=-O2 -march=i486
#CFLAGS=-g -Wall
CPPFLAGS=-D__WIN32
OBJS=linkedlist.o main.o md4.o processfile.o

TARGET=ed2k_hash.exe

OBJS+=cl_ui.o options.o

$(TARGET): $(OBJS)
	$(CC) -o $(TARGET) $(OBJS)

